spring.application.name=devops-health-monitor
spring.datasource.url=jdbc:h2:mem:devopsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.password=
spring.datasource.username=sa

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true

management.otlp.metrics.export.enabled=false

# Если бот со статусом RUNNING не присылал heartbeat дольше N минут - помечаем его DOWN
app.bot.heartbeat-timeout-minutes=5
# Как часто проверяем ботов на "молчание" (в мс)
app.bot.heartbeat-check-interval-ms=60000

