CREATE TABLE trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_id BIGINT NOT NULL REFERENCES bots (id),
    symbol VARCHAR(255) NOT NULL,
    side VARCHAR(255) NOT NULL CHECK (side IN ('BUY', 'SELL')),
    quantity NUMERIC(18, 8) NOT NULL,
    price NUMERIC(18, 8) NOT NULL,
    pnl NUMERIC(18, 8),
    executed_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_trades_bot_id ON trades (bot_id);
