CREATE TABLE decision_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_id BIGINT NOT NULL REFERENCES bots (id),
    action VARCHAR(255) NOT NULL,
    reasoning TEXT,
    timestamp TIMESTAMP NOT NULL
);

CREATE INDEX idx_decision_logs_bot_id ON decision_logs (bot_id);
