CREATE TABLE trade_proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_id BIGINT NOT NULL REFERENCES bots (id),
    symbol VARCHAR(255) NOT NULL,
    side VARCHAR(255) NOT NULL CHECK (side IN ('BUY', 'SELL')),
    quantity NUMERIC(18, 8) NOT NULL,
    price NUMERIC(18, 8) NOT NULL,
    reasoning TEXT,
    status VARCHAR(255) NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    created_at TIMESTAMP NOT NULL,
    decided_at TIMESTAMP
);

CREATE INDEX idx_trade_proposals_bot_id ON trade_proposals (bot_id);
CREATE INDEX idx_trade_proposals_status ON trade_proposals (status);
